day_number = int(input("Enter day number: "))
if(day_number == 1): print("today is Monday")
elif (day_number == 2): print("today is Tuesday")
elif (day_number == 3): print("today is Wednesday")
elif (day_number == 4): print("today is Thursday")
elif (day_number == 5): print("today is Friday")
elif (day_number == 6): print("today is Saturday")
elif (day_number == 7): print("today is Sonday")
else: print("You Entered a Wrong DayNumber")
